# This file controls what tables are imported from bell into the worklists2 tool. The format is
# <wl2_table>:
  #:table_name: <bell_table>
  #:rename_columns:
    #<bell_column>: <wl2_column>
 
# The rename_columns option is to help fit the kb3 legacy table structure into Rails conventions: 
#
# * None of the wl2 tables created from bell tables have autoincrementing primary keys
# because these would show up in urls but not be consistent across imports due
# to record deletions, which would cause the urls to break after an import.
#
# * most have string identity columns I have renamed on import (see the old/new name pairs in
# :rename_columns keys below) to 'id'.
#
# E.g., in the titles table, having the foreign key "audience"
# makes Hobo think that the title model has an "audience" attribute rather than
# just a fk relationship with the audience model. So after renaming the foreign
# key to audience_id, Rails will create the join sql automatically if the column
# referred to by the fk 'audience_id' in the audiences table is named 'id'.

docs: 
  :table_name: document
  :rename_columns:
    author: author_id
    owner: owner_id
    visibility: visibility_id
    volatility: volatility_id
    status: status_id
    importance: importance_id

boilers:
  :table_name: documentnames
  :rename_columns:
    docid: doc_id
    
expirations:
    :table_name: expire
    :rename_columns:
        id: doc_id
        expiredate: date
        explanation: reason

hotitems:
    :table_name: hotitem
    :rename_columns:
        id: doc_id
        hotitem: name

kbresources:
  :table_name: kbresource
  :rename_columns:
    id: doc_id
    username: kbuser_id
    
kbusers:
    :table_name: kbuser
    :rename_columns:
        username: id
        
titles:
  :table_name: titlecache
  :rename_columns:
    audience: audience_id
    docid: doc_id
    
audiences:
  :table_name: titleaudience
  :rename_columns:
    audience: id
    
domains:
  :table_name: domainlist
  :rename_columns:
    class: domain_class
    domain: id
    type: domain_type

domained_docs:
  :table_name: documentdomain
  :rename_columns:
    id: doc_id
    domain: domain_id
    
importances:
  :table_name: importance
  :rename_columns:
    importance: name
    rank: id

visibilities:
  :table_name: visibility
  :rename_columns:
    visibility: name
    rank: id

volatilities:
  :table_name: volatility
  :rename_columns:
    volatility: name
    rank: id

statuses:
  :table_name: status
  :rename_columns:
    status: name
    rank: id
