class SearchesController < ApplicationController

  hobo_model_controller

  auto_actions :all

  def show
    @search = find_instance
    # add scopes that pertain only to this display (e.g., including the
    # default title, visibility, and volatility, and setting a sort order)
    # and then paginate the search's "docs"
    # association proxy object generated by Search#filter
    @unpaginated_result_docs = @search.filter.apply_scopes(
      :include_default_title => true,
      :include_visibility => true,
      :include_volatility => true,
      :order_by => parse_sort_param(:id, :default_title, :visibility_assoc,
        :volatility_assoc, :birthdate, :modifieddate, :approveddate)
    )

    hobo_show do |format|
      format.html do
        @result_docs = @unpaginated_result_docs.paginate(
      :page => params[:page])
      end
      format.xml do
        # FIXME: the following used to work but now gives "wrong number of arguments (1 for 0)"
        # See http://archive.patmaddox.com/blog/2007/2/22/my-rails-gotcha-custom-to_xml-in-a-hash-or-array
        # not sure what to do.
        # FIXME: Moved format.xml below format.html because when testing
        # capybara and Rack.test followed the :xml path when it was first even when not
        # requesting xml.
        render :xml => [@search, @unpaginated_result_docs]
      end
    end
  end
end
